[app]
GOOGLE_API_KEY = "AlzaSyBfu_mmKeCiwU2HCdtvr-_IzUrF0_7NxwY"
MONGODB_URI = "mongodb+srv://francheskaordonez_db_userpgnB6eupRagQFQQC@fhor.mxhscmz.mongodb.net/?appName=FHOR"
USER = "FRANCHESKA HITTOMY ORDOÃ‘EZ RAMOS"
COHERE_API_KEY = "Mka1Vr6bjcjYPC07t3GOwLSxtIPPFoOqtVUQC5YM"

[b2]
B2_BUCKET_NAME = "FHOR-PC2"
B2_READ_KEY_ID = "005dc8e086321330000000001"
B2_READ_APPLICATION_KEY = "K0052GW2Is2A4yPFRxsbi1rxPcPBF+g"
B2_WRITE_KEY_ID = "005dc8e086321330000000002"
B2_WRITE_APPLICATION_KEY = "K005+rlQu3kERqmYVuOFCIW/7hUWmlQ"
B2_BUCKET_ID = "ed2c287e2068b67392a10313"

